<?php
add_action( 'init', 'studiojogikp_cpts_wyjazdy' );
function studiojogikp_cpts_wyjazdy() {
	$labels = array(
		"name" => __( 'Wyjazdy', 'studiojogikp' ),
		"singular_name" => __( 'Wyjazd', 'studiojogikp' ),
		);

	$args = array(
		"label" => __( 'wyjazdy', 'studiojogikp' ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => true,
		"exclude_from_search" => false,
        "menu_icon" => "dashicons-palmtree",
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "wyjazdy", "with_front" => true ),
		"query_var" => true,
		
		"supports" => array( "title", "editor", "thumbnail", "excerpt" ),		
			);
	register_post_type( "sjkp_wyjazdy", $args );

// End
}

add_action( 'init', 'studiojogikp_cpts_szkolenia' );
function studiojogikp_cpts_szkolenia() {
	$labels = array(
		"name" => __( 'Szkolenia', 'studiojogikp' ),
		"singular_name" => __( 'Szkolenie', 'studiojogikp' ),
		);

	$args = array(
		"label" => __( 'Szkolenia', 'studiojogikp' ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => true,
		"exclude_from_search" => false,
        "menu_icon" => "dashicons-star-filled",
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "szkolenia", "with_front" => true ),
		"query_var" => true,
		
		"supports" => array( "title", "editor", "thumbnail", "excerpt" ),		
			);
	register_post_type( "sjkp_szkolenia", $args );

// End
}

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function informacje_o_wyjedzie_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function informacje_o_wyjedzie_add_meta_box() {
	add_meta_box(
		'informacje_o_wyjedzie-informacje-o-wyjedzie',
		__( 'informacje o wyjeździe', 'informacje_o_wyjedzie' ),
		'informacje_o_wyjedzie_html',
		'sjkp_wyjazdy',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'informacje_o_wyjedzie_add_meta_box' );

function informacje_o_wyjedzie_html( $post) {
	wp_nonce_field( '_informacje_o_wyjedzie_nonce', 'informacje_o_wyjedzie_nonce' ); ?>
    <p>
        <label for="informacje_o_wyjedzie_termin_wyjazdu">
            <?php _e( 'termin wyjazdu', 'informacje_o_wyjedzie' ); ?>
        </label>
        <br>
        <input type="text" name="informacje_o_wyjedzie_termin_wyjazdu" id="informacje_o_wyjedzie_termin_wyjazdu" value="<?php echo informacje_o_wyjedzie_get_meta( 'informacje_o_wyjedzie_termin_wyjazdu' ); ?>"> </p>
    <p>
        <label for="informacje_o_wyjedzie_miejsce">
            <?php _e( 'miejsce', 'informacje_o_wyjedzie' ); ?>
        </label>
        <br>
        <input type="text" name="informacje_o_wyjedzie_miejsce" id="informacje_o_wyjedzie_miejsce" value="<?php echo informacje_o_wyjedzie_get_meta( 'informacje_o_wyjedzie_miejsce' ); ?>"> </p>
    <p>
        <label for="informacje_o_wyjedzie_koszt">
            <?php _e( 'koszt', 'informacje_o_wyjedzie' ); ?>
        </label>
        <br>
        <input type="text" name="informacje_o_wyjedzie_koszt" id="informacje_o_wyjedzie_koszt" value="<?php echo informacje_o_wyjedzie_get_meta( 'informacje_o_wyjedzie_koszt' ); ?>"> </p>
    <?php
}

function informacje_o_wyjedzie_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['informacje_o_wyjedzie_nonce'] ) || ! wp_verify_nonce( $_POST['informacje_o_wyjedzie_nonce'], '_informacje_o_wyjedzie_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['informacje_o_wyjedzie_termin_wyjazdu'] ) )
		update_post_meta( $post_id, 'informacje_o_wyjedzie_termin_wyjazdu', esc_attr( $_POST['informacje_o_wyjedzie_termin_wyjazdu'] ) );
	if ( isset( $_POST['informacje_o_wyjedzie_miejsce'] ) )
		update_post_meta( $post_id, 'informacje_o_wyjedzie_miejsce', esc_attr( $_POST['informacje_o_wyjedzie_miejsce'] ) );
	if ( isset( $_POST['informacje_o_wyjedzie_koszt'] ) )
		update_post_meta( $post_id, 'informacje_o_wyjedzie_koszt', esc_attr( $_POST['informacje_o_wyjedzie_koszt'] ) );
}
add_action( 'save_post', 'informacje_o_wyjedzie_save' );

/*
	Usage: informacje_o_wyjedzie_get_meta( 'informacje_o_wyjedzie_termin_wyjazdu' )
	Usage: informacje_o_wyjedzie_get_meta( 'informacje_o_wyjedzie_miejsce' )
	Usage: informacje_o_wyjedzie_get_meta( 'informacje_o_wyjedzie_koszt' )
*/

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function informacje_o_szkoleniu_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function informacje_o_szkoleniu_add_meta_box() {
	add_meta_box(
		'informacje_o_szkoleniu-informacje-o-szkoleniu',
		__( 'informacje o szkoleniu', 'informacje_o_szkoleniu' ),
		'informacje_o_szkoleniu_html',
		'sjkp_szkolenia',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'informacje_o_szkoleniu_add_meta_box' );

function informacje_o_szkoleniu_html( $post) {
	wp_nonce_field( '_informacje_o_szkoleniu_nonce', 'informacje_o_szkoleniu_nonce' ); ?>
        <div>
            <label for="informacje_o_szkoleniu_termin_szkolenia">
                <?php _e( 'termin szkolenia', 'informacje_o_szkoleniu' ); ?>
            </label>
            <br>
            <input type="text" name="informacje_o_szkoleniu_termin_szkolenia" id="informacje_o_szkoleniu_termin_szkolenia" value="<?php echo informacje_o_szkoleniu_get_meta( 'informacje_o_szkoleniu_termin_szkolenia' ); ?>"> </div>
        <p>
            <label for="informacje_o_szkoleniu_miejsce">
                <?php _e( 'miejsce', 'informacje_o_szkoleniu' ); ?>
            </label>
            <br>
            <input type="text" name="informacje_o_szkoleniu_miejsce" id="informacje_o_szkoleniu_miejsce" value="<?php echo informacje_o_szkoleniu_get_meta( 'informacje_o_szkoleniu_miejsce' ); ?>"> </p>
        <p>
            <label for="informacje_o_szkoleniu_cena">
                <?php _e( 'cena', 'informacje_o_szkoleniu' ); ?>
            </label>
            <br>
            <input type="text" name="informacje_o_szkoleniu_cena" id="informacje_o_szkoleniu_cena" value="<?php echo informacje_o_szkoleniu_get_meta( 'informacje_o_szkoleniu_cena' ); ?>"> </p>
        <?php
}

function informacje_o_szkoleniu_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['informacje_o_szkoleniu_nonce'] ) || ! wp_verify_nonce( $_POST['informacje_o_szkoleniu_nonce'], '_informacje_o_szkoleniu_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['informacje_o_szkoleniu_termin_szkolenia'] ) )
		update_post_meta( $post_id, 'informacje_o_szkoleniu_termin_szkolenia', esc_attr( $_POST['informacje_o_szkoleniu_termin_szkolenia'] ) );
	if ( isset( $_POST['informacje_o_szkoleniu_miejsce'] ) )
		update_post_meta( $post_id, 'informacje_o_szkoleniu_miejsce', esc_attr( $_POST['informacje_o_szkoleniu_miejsce'] ) );
	if ( isset( $_POST['informacje_o_szkoleniu_cena'] ) )
		update_post_meta( $post_id, 'informacje_o_szkoleniu_cena', esc_attr( $_POST['informacje_o_szkoleniu_cena'] ) );
}
add_action( 'save_post', 'informacje_o_szkoleniu_save' );

/*
	Usage: informacje_o_szkoleniu_get_meta( 'informacje_o_szkoleniu_termin_szkolenia' )
	Usage: informacje_o_szkoleniu_get_meta( 'informacje_o_szkoleniu_miejsce' )
	Usage: informacje_o_szkoleniu_get_meta( 'informacje_o_szkoleniu_cena' )
*/

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function prowadzcy_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function prowadzcy_add_meta_box() {
	add_meta_box(
		'prowadzcy-prowadzcy',
		__( 'prowadzący', 'prowadzcy' ),
		'prowadzcy_html',
		'sjkp_szkolenia',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'prowadzcy_add_meta_box' );

function prowadzcy_html( $post) {
	wp_nonce_field( '_prowadzcy_nonce', 'prowadzcy_nonce' ); ?>
            <div class="inside">
                <p>
                    <label for="prowadzcy_imi_i_nazwisko">
                        <?php _e( 'imię i nazwisko', 'prowadzcy' ); ?>
                    </label>
                    <br>
                    <input type="text" name="prowadzcy_imi_i_nazwisko" id="prowadzcy_imi_i_nazwisko" value="<?php echo prowadzcy_get_meta( 'prowadzcy_imi_i_nazwisko' ); ?>"> </p>
                <p>
                    <label for="prowadzcy_o_prowadzcym">
                        <?php _e( 'o prowadzącym', 'prowadzcy' ); ?>
                    </label>
                    <br>
                    <textarea name="prowadzcy_o_prowadzcym" id="prowadzcy_o_prowadzcym">
                        <?php echo prowadzcy_get_meta( 'prowadzcy_o_prowadzcym' ); ?>
                    </textarea>
                </p>
            </div>
            <?php
}

function prowadzcy_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['prowadzcy_nonce'] ) || ! wp_verify_nonce( $_POST['prowadzcy_nonce'], '_prowadzcy_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['prowadzcy_imi_i_nazwisko'] ) )
		update_post_meta( $post_id, 'prowadzcy_imi_i_nazwisko', esc_attr( $_POST['prowadzcy_imi_i_nazwisko'] ) );
	if ( isset( $_POST['prowadzcy_o_prowadzcym'] ) )
		update_post_meta( $post_id, 'prowadzcy_o_prowadzcym', esc_attr( $_POST['prowadzcy_o_prowadzcym'] ) );
}
add_action( 'save_post', 'prowadzcy_save' );

/*
	Usage: prowadzcy_get_meta( 'prowadzcy_imi_i_nazwisko' )
	Usage: prowadzcy_get_meta( 'prowadzcy_o_prowadzcym' )
*/